"""Add coupon models and relationships

Revision ID: 702cffddfcfc
Revises: 661e31f77534
Create Date: 2025-06-18 21:51:57.454962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702cffddfcfc'
down_revision: Union[str, None] = '661e31f77534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='优惠券名称'),
    sa.Column('code_prefix', sa.String(length=20), nullable=True, comment='优惠券码前缀'),
    sa.Column('type', sa.Enum('FIXED', 'PERCENTAGE', name='coupontype'), nullable=False, comment='优惠券类型'),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False, comment='面值或折扣率'),
    sa.Column('min_spend', sa.Numeric(precision=10, scale=2), nullable=False, comment='最低消费金额'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True, comment='有效期开始时间'),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True, comment='有效期结束时间'),
    sa.Column('total_quantity', sa.Integer(), nullable=False, comment='发行总量, 0为不限制'),
    sa.Column('issued_quantity', sa.Integer(), nullable=False, comment='已发行数量'),
    sa.Column('usage_limit_per_user', sa.Integer(), nullable=False, comment='每位用户可领取/使用上限'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_templates_code_prefix'), 'coupon_templates', ['code_prefix'], unique=True)
    op.create_index(op.f('ix_coupon_templates_id'), 'coupon_templates', ['id'], unique=False)
    op.create_table('user_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_template_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='唯一的优惠券码'),
    sa.Column('status', sa.Enum('UNUSED', 'USED', 'EXPIRED', name='couponstatus'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False, comment='领取时间'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='使用时间'),
    sa.ForeignKeyConstraint(['coupon_template_id'], ['coupon_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_coupons_code'), 'user_coupons', ['code'], unique=True)
    op.create_index(op.f('ix_user_coupons_coupon_template_id'), 'user_coupons', ['coupon_template_id'], unique=False)
    op.create_index(op.f('ix_user_coupons_id'), 'user_coupons', ['id'], unique=False)
    op.create_index(op.f('ix_user_coupons_status'), 'user_coupons', ['status'], unique=False)
    op.create_index(op.f('ix_user_coupons_user_id'), 'user_coupons', ['user_id'], unique=False)
    op.add_column('orders', sa.Column('user_coupon_id', sa.Integer(), nullable=True, comment='使用的优惠券ID'))
    op.create_unique_constraint(None, 'orders', ['user_coupon_id'])
    op.create_foreign_key(None, 'orders', 'user_coupons', ['user_coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'user_coupon_id')
    op.drop_index(op.f('ix_user_coupons_user_id'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_status'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_id'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_coupon_template_id'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_code'), table_name='user_coupons')
    op.drop_table('user_coupons')
    op.drop_index(op.f('ix_coupon_templates_id'), table_name='coupon_templates')
    op.drop_index(op.f('ix_coupon_templates_code_prefix'), table_name='coupon_templates')
    op.drop_table('coupon_templates')
    # ### end Alembic commands ###
