"""add coupon fields to order table

Revision ID: 92fbec5f7676
Revises: 702cffddfcfc
Create Date: 2025-06-19 17:12:37.130582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92fbec5f7676'
down_revision: Union[str, None] = '702cffddfcfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - manually adjusted ###
    # op.add_column('orders', sa.Column('coupon_discount_amount', sa.Numeric(precision=10, scale=2), nullable=False,
    #                                   comment='优惠券抵扣金额'))
    op.alter_column('orders', 'user_coupon_id',
                    existing_type=mysql.INTEGER(),
                    comment='使用的用户优惠券ID',
                    existing_comment='使用的优惠券ID',
                    existing_nullable=True)

    # Manually adjusted section to solve foreign key dependency issue
    # Step 1: Drop the existing foreign key constraint.
    # IMPORTANT: Replace 'YOUR_FK_CONSTRAINT_NAME_HERE' with the actual name from your database.
    op.drop_constraint('orders_ibfk_3', 'orders', type_='foreignkey')

    # Step 2: Now it's safe to drop the index.
    op.drop_index('user_coupon_id', table_name='orders')

    # Step 3: Recreate the foreign key constraint.
    op.create_foreign_key(
        'fk_orders_user_coupon_id_user_coupons',  # A new name for the constraint
        'orders', 'user_coupons',
        ['user_coupon_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - manually adjusted ###

    # Manually adjusted section (reverses the upgrade)
    # Step 1: Drop the recreated foreign key.
    op.drop_constraint('fk_orders_user_coupon_id_user_coupons', 'orders', type_='foreignkey')

    # Step 2: Recreate the unique index.
    op.create_index('user_coupon_id', 'orders', ['user_coupon_id'], unique=True)

    # Step 3: Recreate the original foreign key, which depends on the unique index.
    # IMPORTANT: Use the same original name you found for the upgrade step.
    op.create_foreign_key(
        'orders_ibfk_3',
        'orders', 'user_coupons',
        ['user_coupon_id'], ['id']
    )

    # Original downgrade commands
    op.alter_column('orders', 'user_coupon_id',
                    existing_type=mysql.INTEGER(),
                    comment='使用的优惠券ID',
                    existing_comment='使用的用户优惠券ID',
                    existing_nullable=True)
    # op.drop_column('orders', 'coupon_discount_amount')
    # ### end Alembic commands ###
