"""Add promotion table and link to order

Revision ID: ec050c5664ee
Revises: 0f56c1a527a6
Create Date: 2025-06-17 22:28:01.914255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec050c5664ee'
down_revision: Union[str, None] = '0f56c1a527a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='促销活动名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='促销活动描述'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('target_type', sa.Enum('ALL', 'PRODUCT', 'CATEGORY', 'TAG', name='promotiontargettype'), nullable=False, comment='促销适用目标类型'),
    sa.Column('target_ids', sa.JSON(), nullable=True, comment='目标ID列表，根据target_type决定内容'),
    sa.Column('condition_type', sa.Enum('NO_THRESHOLD', 'MIN_AMOUNT', 'MIN_QUANTITY', name='promotionconditiontype'), nullable=False, comment='触发条件类型'),
    sa.Column('condition_value', sa.Numeric(precision=10, scale=2), nullable=True, comment='触发条件的值（如满100元，则为100）'),
    sa.Column('action_type', sa.Enum('FIXED', 'PERCENTAGE', name='promotionactiontype'), nullable=False, comment='优惠动作类型'),
    sa.Column('action_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='优惠动作的值（如减10元则为10，打8折则为80）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_id'), 'promotion', ['id'], unique=False)
    op.add_column('orders', sa.Column('promotion_id', sa.Integer(), nullable=True, comment='应用的促销活动ID'))
    op.create_foreign_key(None, 'orders', 'promotion', ['promotion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'promotion_id')
    op.drop_index(op.f('ix_promotion_id'), table_name='promotion')
    op.drop_table('promotion')
    # ### end Alembic commands ###
