"""Add seckill models

Revision ID: fb350b058c2a
Revises: 92fbec5f7676
Create Date: 2025-06-20 10:36:37.732182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb350b058c2a'
down_revision: Union[str, None] = '92fbec5f7676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seckill_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='活动名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='活动描述'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='秒杀开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='秒杀结束时间'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ENDED', 'CANCELLED', name='seckillactivitystatus'), nullable=False, comment='活动状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seckill_activities_id'), 'seckill_activities', ['id'], unique=False)
    op.create_table('seckill_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False, comment='秒杀活动ID'),
    sa.Column('sku_id', sa.Integer(), nullable=False, comment='商品SKUID'),
    sa.Column('seckill_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='秒杀价'),
    sa.Column('seckill_stock', sa.Integer(), nullable=False, comment='秒杀库存'),
    sa.Column('purchase_limit', sa.Integer(), nullable=False, comment='每人限购数量'),
    sa.ForeignKeyConstraint(['activity_id'], ['seckill_activities.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seckill_products_id'), 'seckill_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seckill_products_id'), table_name='seckill_products')
    op.drop_table('seckill_products')
    op.drop_index(op.f('ix_seckill_activities_id'), table_name='seckill_activities')
    op.drop_table('seckill_activities')
    # ### end Alembic commands ###
